name: Build-Push-Deploy

on:
  push:
    branches:
      - main

    paths:
      - 'wisecow.sh'
      - 'Dockerfile'
      - '.github/workflows/**'
  

env:
  IMAGE_NAME: wisecow

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:${IMAGE_TAG} .

      - name: Push Image
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:${IMAGE_TAG}

      - name: Update Deployment Manifest
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:${IMAGE_TAG}|g" kubernetes/deployment.yml

      - name: Commit Updated Manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add kubernetes/deployment.yml

          git commit -m "Update image tag ${IMAGE_TAG}" || exit 0

          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          
